[font]
normal = { family = "FiraMono Nerd Font Mono" }
size = 18

[window]
opacity = 0.75
padding.x = 0
padding.y = 0
dimensions.columns = 140
dimensions.lines = 40

[general]
import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]
