[font]
normal = { family = "FiraMono Nerd Font Mono" }
size = 16 

[window]
opacity = 0.9
padding.x = 0
padding.y = 0
dimensions.columns = 150 
dimensions.lines = 50 

[general]
import  = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]
